### ISSUE TITLE
react-router - Passo a Passo Redux

### ISSUE THREAD

**Issue by oieduardorabelo** [marcoshs90/react-redux-router-completed#2]
@marcoshs90, você tem alguns problemas com o react-router sim,

- Em **app/index.js L:22**, você está importando o **containers/topics/TopicsScreen** como **App**, porém, esse componente não está renderizando o **.children**, impossibilitando as sub-rotas de serem renderizadas dentro do **App** (como você definiu ele como o container de todas as rotas, você precisa renderizar os childrens)
- Em app/index.js L:23, você está usando um **pathless route** (sem o "/" no começo), recomendo você dar uma lida no [Route Configuration](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md) para evitar problemas inesperados, com e sem a "/" tem efeitos bem diferentes.

Achei estranho você ter um **app/containers/App.js**, é idêntico ao client/App, mas vi que você não está usando, então seja só referência! :)

🎉

**Comment by marcoshs90** [comment]
Obrigado pela resposta Eduardo, mas já resolvi isso.

somente não fiz o merge da branch para atualizar isso, usei das props da children e fiz validação da autenticação com o requireAuth do redux mesmo.

Vlw mesmo, se achar algo no codigo que pode ser melhorado é sempre bom opiniões de fora.
